spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
#    hikari:
#      max-lifetime: 540000
#      maximum-pool-size: 3
#      idle-timeout: 120000
