spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    hikari:
      max-lifetime: 540000
      maximum-pool-size: 3
      idle-timeout: 120000
  liquibase:
    change-log: 'classpath:/db/liquibase-changelog.xml'

application:
  api-url: ${API_URL}
  mercadopago:
    access-token: ${MERCADOPAGO_TOKEN}
  jwt:
    secret: ${JWT_SECRET}

server:
  error:
    include-stacktrace: never